on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Build
        run: bazel build //:bazel-bep-protobuf
      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(grep -oP 'BAZEL_VERSION=\K[^\s]+' MODULE.bazel)
          echo "::set-output name=version::$VERSION"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bazel-bin/bazel-bep-protobuf.jar
          tag_name: ${{ steps.extract_version.outputs.version }}
          body: |
            Bazel BEP Protobuf ${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
